//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdBitacora { get; set; }
        public long Paso { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Parametros { get; set; }
        public string Resultado { get; set; }
        public string Exception { get; set; }
        public string Proceso { get; set; }
        public Nullable<int> Referencia { get; set; }
        public string Origen { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
