//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Tablas
    {
        public long IdBitacoraTablas { get; set; }
        public string EstadoActual { get; set; }
        public string EstadoNuevo { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
