//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Conexiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogo_Conexiones()
        {
            this.Configuracion = new HashSet<Configuracion>();
        }
    
        public int IdConexion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoBD { get; set; }
        public Nullable<int> IdServidor { get; set; }
        public Nullable<int> IdBaseDatos { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Base_De_Datos Base_De_Datos { get; set; }
        public virtual Servidor Servidor { get; set; }
        public virtual Tipos_Base_De_Datos Tipos_Base_De_Datos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuracion> Configuracion { get; set; }
    }
}
