//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IdConfiguracionProceso { get; set; }
        public long IdConfiguracion { get; set; }
        public Nullable<long> IdProcedimientoFuncion { get; set; }
        public Nullable<int> IdConexion { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Catalogo_Conexiones Catalogo_Conexiones { get; set; }
        public virtual Catalogo_Procedimientos_Funciones Catalogo_Procedimientos_Funciones { get; set; }
    }
}
