//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructuras_De_Base_Datos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estructuras_De_Base_Datos()
        {
            this.Catalogo_Procedimientos_Funciones = new HashSet<Catalogo_Procedimientos_Funciones>();
        }
    
        public int IdEstructura { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogo_Procedimientos_Funciones> Catalogo_Procedimientos_Funciones { get; set; }
    }
}
