//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenericsEntities : DbContext
    {
        public GenericsEntities()
            : base("name=GenericsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_De_Datos> Base_De_Datos { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Bitacora_Tablas> Bitacora_Tablas { get; set; }
        public virtual DbSet<Catalogo_Conexiones> Catalogo_Conexiones { get; set; }
        public virtual DbSet<Catalogo_Procedimientos_Funciones> Catalogo_Procedimientos_Funciones { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Empresa_Pais> Empresa_Pais { get; set; }
        public virtual DbSet<Estructuras_De_Base_Datos> Estructuras_De_Base_Datos { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<Procedimiento_Funcion_Parametro> Procedimiento_Funcion_Parametro { get; set; }
        public virtual DbSet<Servidor> Servidor { get; set; }
        public virtual DbSet<Tipos_Base_De_Datos> Tipos_Base_De_Datos { get; set; }
    }
}
