//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstAPIGeneric.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimiento_Funcion_Parametro
    {
        public long IdParametro { get; set; }
        public long IdProcedimientoFuncion { get; set; }
        public string TipoDato { get; set; }
        public Nullable<long> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Catalogo_Procedimientos_Funciones Catalogo_Procedimientos_Funciones { get; set; }
        public virtual Parametro Parametro { get; set; }
    }
}
